global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Hapus job mlflow-model karena tidak ada endpoint /metrics
  # - job_name: 'mlflow-model'
  #   static_configs:
  #     - targets: ['host.docker.internal:8080']
  #   metrics_path: '/metrics'

  - job_name: 'custom-metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s